name: Custom Samsung Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Grant Execute Permission to Gradle
      run: chmod +x gradlew

    - name: Compile Samsung APK
      run: ./gradlew assembleDebug -x test -x lint -x detekt --no-daemon

    - name: Upload Clean Installer APK
      uses: actions/upload-artifact@v4
      with:
        name: termux-samsung-a16-build
        path: app/build/outputs/apk/debug/**/*.apk
